### ISSUE TITLE
Hot3DAssets and Hot3DAria are NOT downloaded with error code 403

### ISSUE THREAD

**Issue by Droliven** [facebookresearch/hot3d#3] opened 2024-06-20 17:03 UTC
By following the instructions in README.md, I was able to successfully download the Hot3DQuest data. However, I encountered an error "An error occurred: 403 Client Error" when attempting to download the Hot3DAssets and Hot3DAria data. Could you please provide some help?

**Comment by SeaOtocinclus** [comment] 2024-06-20 17:14
Hi, thank you for your feedback, we are investigating and will come back to you.

**Comment by SeaOtocinclus** [comment] 2024-06-20 17:18
Investigation is still running but so far we have found that all public link are providing the same error (including Quest data, aka. providing the http answer `URL signature expired`)

**Comment by SeaOtocinclus** [comment] 2024-06-21 15:16
@Droliven the issue is now fixed, and download is back to normal.

**Comment by Droliven** [comment] 2024-06-21 17:47
Yes, now it runs well, thks.



---- Replied Message ----
| From | Pierre Moulon @ ***@***.***> |
| Date | 06/21/2024 23:16 |
| To | ***@***.***> |
| Cc | Levon ***@***.***>***@***.***> |
| Subject | Re: [facebookresearch/hot3d] Hot3DAssets and Hot3DAria are NOT downloaded with error code 403 (Issue #3) |

@Droliven the issue is now fixed, and download is back to normal.

**Closed** 2024-06-24 15:32 UTC
